# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zhaohaonan/Desktop/北大资料/Coding/C++/程序设计实习/QT-goldMiner/goldMiner/startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.setEnabled(True)
        StartWindow.resize(1308, 1149)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setStyleSheet("background-image: url(\"../goldMiner/Images/begin.png\");\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 280, 501, 211))
        self.pushButton.setStyleSheet("background-image: url(\"../goldMiner/Images/start.png\");\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        StartWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(StartWindow)
        self.statusBar.setObjectName("statusBar")
        StartWindow.setStatusBar(self.statusBar)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "MainWindow"))
